# Generated by Django 4.2.7 on 2023-11-28 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('nationality', models.CharField(choices=[('ARG', 'Argentina'), ('ESP', 'España'), ('BRA', 'Brasil')], max_length=3, verbose_name='Nacionalidad')),
                ('role', models.CharField(choices=[('técnico', 'Técnico'), ('asistente', 'Asistente'), ('médico', 'Médico'), ('preparador', 'Preparador')], max_length=20, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'db_table': 'tecnico',
            },
        ),
        migrations.CreateModel(
            name='PlayingPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Posición de juego',
                'verbose_name_plural': 'Posiciones de juego',
                'db_table': 'posicion_juego',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('flag_image', models.ImageField(upload_to='flags/', verbose_name='Imagen de Bandera')),
                ('shield_image', models.ImageField(upload_to='shields/', verbose_name='Escudo del Equipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipo',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('position', models.CharField(max_length=50, verbose_name='Posición en la que juega')),
                ('number', models.IntegerField(verbose_name='Número de camiseta')),
                ('is_starting', models.BooleanField(verbose_name='¿Es titular?')),
                ('photo', models.ImageField(upload_to='players/', verbose_name='Foto del jugador')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'jugador',
            },
        ),
    ]
